# Generated by Django 4.0.5 on 2022-06-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_two', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='image',
        ),
    ]
