# Generated by Django 4.0.5 on 2022-06-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_two', '0003_deck_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=100, verbose_name='producer name')),
            ],
        ),
    ]
